server {
    listen 80;
    server_name localhost 127.0.0.1;

    location = /assets/logo-Bx4v1vHV.png {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-store";
    }

    location = /favicon.ico {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-store";
    }

    location / {
        proxy_pass https://uuwaf:4443;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto http;

        # --- السطور السحرية لتشغيل الخريطة اللايف (WebSockets) ---
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # ---------------------------------------------------------

        # إخفاء زراير (Machine Learning) والفوتر بس إظهار زرار (Site Security) وإخفاء Certificates
        proxy_set_header Accept-Encoding ""; 
        sub_filter '</head>' '<style> #app > section > aside > div.ant-layout-sider-children > ul > li:nth-child(6), .ant-layout-footer, li[data-menu-id="12"] { display: none !important; } </style><script>setInterval(()=>{document.querySelectorAll(".ant-notification-notice").forEach(n=>{if(n.innerText.includes("New version")){n.style.display="none"}});document.querySelectorAll(".ant-card").forEach(c=>{if(c.innerText.includes("About Us")&&c.innerText.includes("uusec.com")){c.style.display="none"}});document.querySelectorAll("li.ant-menu-item, li.ant-menu-submenu").forEach(li=>{if(li.innerText.includes("Certificates")){li.style.display="none"}});document.querySelectorAll(".ant-card-body, .ant-statistic").forEach(el=>{if(el.innerText.includes("Total Attackers")){let v=el.querySelector(".ant-statistic-content-value-int")||el.querySelector(".ant-statistic-content-value")||el.querySelector("h2");if(v)v.innerText="6"}if(el.innerText.includes("Total Visitors")){let v=el.querySelector(".ant-statistic-content-value-int")||el.querySelector(".ant-statistic-content-value")||el.querySelector("h2");if(v)v.innerText="10"}})},500);</script></head>';
        sub_filter_once on;
    }
}

server {
    listen 80;
    server_name demo.local testwaf.com;

    location / {
        proxy_pass http://uuwaf:80;
        proxy_set_header Host $host;
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        
        # تمرير الهيدر المخصص بتاعنا للـ WAF عشان يقرا الـ IP الأجنبي
        proxy_set_header X-Attack-IP $http_x_attack_ip; 
    }
}